# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: $(date:yyyyMMdd)$(rev:.r)

#trigger:
#- feature/Test-feature
trigger: none

pool:
  name: 'Azure Pipelines'
  vmImage: 'ubuntu-latest'
  

variables:
  - name: parsed-dockerhub-connection-name
    value: $[variables.docker_registry_sc_name]

stages:
- stage: enforcer_app
  displayName: Enforcer App
  jobs:
  - job: build_api
    displayName: Build and Publish API
    steps:
    
    - task: Docker@2
      displayName: Build Docker Image
      inputs:
        containerRegistry: 'Docker Hub IAGTO Project'
        repository: 'iagtodev/enforcer-attributevalueprovider-issue'
        command: 'build'
        buildContext: '../'
        Dockerfile: 'IAGTO.Enforcer.Api/Dockerfile'
        addPipelineData: false
        tags: '$(Build.BuildNumber)'
    
    - task: Docker@2
      displayName: 'Push Image to Docker Hub'
      condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
      inputs:
        containerRegistry: 'Docker Hub IAGTO Project'
        repository: 'iagtodev/enforcer-attributevalueprovider-issue'
        command: 'push'
        tags: '$(Build.BuildNumber)'